"use client";

import { useEffect, useRef } from "react";
import { regenerateDraftAction } from "@/app/actions";
import type { GameId } from "@/core/types";

type AutoGenerateDraftProps = {
  readonly gameId: GameId;
};

export function AutoGenerateDraft({ gameId }: AutoGenerateDraftProps) {
  const formRef = useRef<HTMLFormElement>(null);
  const submittedRef = useRef(false);

  useEffect(() => {
    if (submittedRef.current) {
      return;
    }

    submittedRef.current = true;
    formRef.current?.requestSubmit();
  }, []);

  return (
    <div className="absolute inset-0 z-10 flex items-center justify-center rounded-lg bg-background/82 backdrop-blur-sm">
      <div className="rounded-md border border-interactive-border bg-background px-4 py-3 text-sm font-medium text-foreground shadow-2xl">
        Generating LLM draft...
      </div>
      <form
        ref={formRef}
        action={regenerateDraftAction.bind(null, gameId)}
        aria-hidden="true"
        className="hidden"
      />
    </div>
  );
}
