"use client";

import { useEffect, useRef } from "react";
import { regenerateDraftAction } from "@/app/actions";
import type { GameId } from "@/core/types";
import { markLlmGenerationPending } from "./llm-generation-notification";

type AutoGenerateDraftProps = {
  readonly gameId: GameId;
  readonly draftId: string;
};

export function AutoGenerateDraft({ gameId, draftId }: AutoGenerateDraftProps) {
  const formRef = useRef<HTMLFormElement>(null);
  const submittedRef = useRef(false);

  useEffect(() => {
    if (submittedRef.current) {
      return;
    }

    submittedRef.current = true;
    markLlmGenerationPending(gameId, draftId, null);
    formRef.current?.requestSubmit();
  }, [draftId, gameId]);

  return (
    <form
      ref={formRef}
      action={regenerateDraftAction.bind(null, gameId)}
      aria-hidden="true"
      className="hidden"
    />
  );
}
