import {
  confirmDraftAction,
  deleteDraftAction,
  editDraftPayloadAction,
  regenerateDraftAction,
} from "@/app/actions";
import { Check, Loader2, RefreshCw, Save, Trash2 } from "lucide-react";
import type { ReactNode } from "react";
import type { DraftEvent } from "@/core/drafts";
import { formatDraftForHost, formatVisibility } from "@/core/event-presenter";
import type { GenerationRecord } from "@/core/generation-record";
import type { PlayerSnapshot } from "@/core/player";
import type { GameId } from "@/core/types";
import { iconButtonClassName } from "@/components/ui/button-styles";
import { AutoGenerateDraft } from "./auto-generate-draft";
import { FormSubmitButton } from "./form-submit-button";
import { LlmGenerationDetails } from "./llm-generation-details";

type DraftPanelProps = {
  readonly gameId: GameId;
  readonly draft: DraftEvent | null;
  readonly players: readonly PlayerSnapshot[];
  readonly generations: readonly GenerationRecord[];
};

export function DraftPanel({
  gameId,
  draft,
  players,
  generations,
}: DraftPanelProps) {
  if (!draft) {
    return (
      <section className="flex h-full min-h-0 flex-col rounded-lg border border-border bg-surface/45">
        <div className="flex shrink-0 items-center justify-between gap-3 border-b border-border px-3 py-2">
          <h2 className="text-sm font-semibold text-foreground">Draft</h2>
        </div>
        <div className="grid flex-1 place-items-center px-4 py-10 text-sm text-subtle">
          No draft pending.
        </div>
      </section>
    );
  }

  const presented = formatDraftForHost(draft, players);
  const latestGeneration = latestGenerationForDraft(generations, draft.id);
  const generatingInitialDraft = isLlmDraft(draft) && !latestGeneration;

  return (
    <section
      aria-busy={generatingInitialDraft}
      className="relative flex h-full min-h-0 flex-col overflow-hidden rounded-lg border border-border bg-surface/45"
    >
      <div className="flex shrink-0 items-center justify-between gap-3 border-b border-border px-3 py-2">
        <h2 className="text-sm font-semibold text-foreground">Draft</h2>
        <div className="flex shrink-0 items-center gap-2">
          {generatingInitialDraft ? <MetaPill>Generating</MetaPill> : null}
          <form action={confirmDraftAction.bind(null, gameId)}>
            <FormSubmitButton
              label={<Check aria-hidden="true" className="h-4 w-4" />}
              pendingLabel={
                <Loader2 aria-hidden="true" className="h-4 w-4 animate-spin" />
              }
              ariaLabel="Confirm draft"
              title="Confirm draft"
              className={iconButtonClassName({ variant: "success" })}
            />
          </form>
          <form action={deleteDraftAction.bind(null, gameId)}>
            <FormSubmitButton
              label={<Trash2 aria-hidden="true" className="h-4 w-4" />}
              pendingLabel={
                <Loader2 aria-hidden="true" className="h-4 w-4 animate-spin" />
              }
              ariaLabel="Delete draft"
              title="Delete draft"
              className={iconButtonClassName({ variant: "danger" })}
            />
          </form>
        </div>
      </div>

      <div className="min-h-0 flex-1 overflow-y-auto">
        <div className="px-3 py-3">
          <div className="flex flex-wrap gap-1.5">
            <MetaPill>{draft.phase}</MetaPill>
            <MetaPill>{formatVisibility(draft.visibility)}</MetaPill>
            <MetaPill>{draft.type}</MetaPill>
          </div>
        </div>

        <section className="border-t border-border px-3 py-4">
          <SectionLabel>Summary</SectionLabel>
          <h3 className="mt-2 break-words text-base font-semibold leading-6 text-foreground">
            {presented.title}
          </h3>
          <p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-muted">
            {presented.text}
          </p>
          {presented.details && presented.details.length > 0 ? (
            <ul className="mt-3 space-y-1.5 border-t border-border pt-3 text-xs text-subtle">
              {presented.details.map((detail) => (
                <li key={detail} className="break-words">
                  {detail}
                </li>
              ))}
            </ul>
          ) : null}
        </section>

        {draft.reason ? (
          <section className="border-t border-border px-3 py-4">
            <SectionLabel>Reason</SectionLabel>
            <p className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-muted">
              {draft.reason}
            </p>
          </section>
        ) : null}

        {latestGeneration ? (
          <section className="border-t border-border px-3 py-4">
            <div className="flex items-start justify-between gap-3">
              <div className="min-w-0">
                <SectionLabel>Generation</SectionLabel>
                <div className="mt-2 flex flex-wrap items-center gap-1.5 text-xs text-muted">
                  <MetaPill>{latestGeneration.status}</MetaPill>
                  <MetaPill>
                    {latestGeneration.provider}/{latestGeneration.model}
                  </MetaPill>
                  <MetaPill>{latestGeneration.promptVersion}</MetaPill>
                </div>
              </div>
              <div className="flex shrink-0 gap-2">
                {isLlmDraft(draft) ? (
                  <form action={regenerateDraftAction.bind(null, gameId)}>
                    <FormSubmitButton
                      label={<RefreshCw aria-hidden="true" className="h-4 w-4" />}
                      pendingLabel={
                        <Loader2
                          aria-hidden="true"
                          className="h-4 w-4 animate-spin"
                        />
                      }
                      ariaLabel="Regenerate"
                      title="Regenerate"
                      className={iconButtonClassName()}
                    />
                  </form>
                ) : null}
                <LlmGenerationDetails generation={latestGeneration} />
              </div>
            </div>
            {latestGeneration.error ? (
              <p className="mt-3 whitespace-pre-wrap break-words rounded-md border border-danger-badge/70 bg-danger-badge/35 px-3 py-2 text-xs leading-5 text-danger-badge-foreground">
                {latestGeneration.error}
              </p>
            ) : null}
          </section>
        ) : null}

        <DraftPayloadForm gameId={gameId} draft={draft} players={players} />
      </div>
      {generatingInitialDraft ? <AutoGenerateDraft gameId={gameId} /> : null}
    </section>
  );
}

function latestGenerationForDraft(
  generations: readonly GenerationRecord[],
  draftId: DraftEvent["id"],
): GenerationRecord | null {
  return (
    [...generations]
      .filter((generation) => generation.draftId === draftId)
      .sort((left, right) => right.createdAt.localeCompare(left.createdAt))[0] ??
    null
  );
}

function SectionLabel({ children }: { readonly children: string }) {
  return (
    <div className="text-[11px] font-semibold uppercase tracking-[0.14em] text-subtle">
      {children}
    </div>
  );
}

function MetaPill({ children }: { readonly children: ReactNode }) {
  return (
    <span className="inline-flex max-w-full items-center rounded-md border border-border bg-surface/75 px-2 py-1 text-[11px] font-medium text-muted">
      <span className="truncate">{children}</span>
    </span>
  );
}

function isLlmDraft(draft: DraftEvent): boolean {
  return (
    draft.type === "day_speech_given" ||
    draft.type === "last_words_given" ||
    draft.type === "pk_speech_given" ||
    draft.type === "wolf_kill_selected" ||
    draft.type === "seer_check_selected" ||
    draft.type === "guard_protect_selected" ||
    draft.type === "hunter_shot_decided" ||
    draft.type === "witch_antidote_decided" ||
    draft.type === "witch_poison_decided" ||
    draft.type === "vote_cast"
  );
}

function DraftPayloadForm({
  gameId,
  draft,
  players,
}: {
  readonly gameId: GameId;
  readonly draft: DraftEvent;
  readonly players: readonly PlayerSnapshot[];
}) {
  const controls = renderDraftPayloadControls(draft, players);

  if (!controls) {
    return null;
  }

  return (
    <form
      action={editDraftPayloadAction.bind(null, gameId)}
      className="border-t border-border px-3 py-4"
    >
      <div className="mb-3 flex items-center justify-between gap-3">
        <SectionLabel>Action payload</SectionLabel>
        <FormSubmitButton
          label={<Save aria-hidden="true" className="h-4 w-4" />}
          pendingLabel={
            <Loader2 aria-hidden="true" className="h-4 w-4 animate-spin" />
          }
          ariaLabel="Save action"
          title="Save action"
          className={iconButtonClassName({ variant: "success" })}
        />
      </div>
      <div className="space-y-3">{controls}</div>
    </form>
  );
}

function renderDraftPayloadControls(
  draft: DraftEvent,
  players: readonly PlayerSnapshot[],
) {
  switch (draft.type) {
    case "wolf_kill_selected":
    case "seer_check_selected":
    case "guard_protect_selected":
    case "hunter_shot_decided":
      return (
        <PlayerTargetField
          label="Target player"
          players={players}
          defaultValue={draft.payload.targetPlayerId}
        />
      );

    case "witch_antidote_decided":
    case "witch_poison_decided":
      return (
        <div className="space-y-3">
          <label className="flex items-center gap-2 text-xs font-medium text-muted">
            <input
              type="checkbox"
              name="used"
              value="true"
              defaultChecked={draft.payload.used}
              className="h-4 w-4 rounded border-interactive-border bg-background text-foreground"
            />
            <span>Use medicine</span>
          </label>
          <input type="hidden" name="used" value="false" />
          <PlayerTargetField
            label="Target player"
            players={players}
            defaultValue={draft.payload.targetPlayerId ?? ""}
            includeEmptyOption
            emptyLabel="No target"
          />
        </div>
      );

    case "last_words_given":
    case "day_speech_given":
    case "pk_speech_given":
      return (
        <label className="block">
          <span className="text-xs font-medium text-muted">Text</span>
          <textarea
            name="text"
            defaultValue={draft.payload.text}
            rows={4}
            className="mt-1 w-full resize-none rounded-md border border-interactive-border bg-background px-3 py-2 text-sm leading-6 text-foreground outline-none transition placeholder:text-subtle focus:border-interactive-border-hover"
          />
        </label>
      );

    case "vote_cast":
      return (
        <PlayerTargetField
          label="Vote target"
          players={players}
          defaultValue={draft.payload.targetPlayerId ?? ""}
          includeEmptyOption
          emptyLabel="Abstain"
        />
      );

    default:
      return null;
  }
}

function PlayerTargetField({
  label,
  players,
  defaultValue,
  includeEmptyOption = false,
  emptyLabel = "Select player",
}: {
  readonly label: string;
  readonly players: readonly PlayerSnapshot[];
  readonly defaultValue: string;
  readonly includeEmptyOption?: boolean;
  readonly emptyLabel?: string;
}) {
  return (
    <label className="block">
      <span className="text-xs font-medium text-muted">{label}</span>
      <select
        name="targetPlayerId"
        defaultValue={defaultValue}
        className="mt-1 w-full rounded-md border border-interactive-border bg-background px-3 py-2 text-sm text-foreground outline-none transition focus:border-interactive-border-hover"
      >
        {includeEmptyOption ? <option value="">{emptyLabel}</option> : null}
        {players.map((player) => (
          <option key={player.playerId} value={player.playerId}>
            {player.seatNo} · {player.name}
          </option>
        ))}
      </select>
    </label>
  );
}
