import type { CharacterDefinition } from "../core/character-definition";

const SEED_TIMESTAMP = "2026-06-27T00:00:00.000Z";
const DEFAULT_PERSONA = "冷静、愿意表达判断";
const DEFAULT_SPEAKING_STYLE = "短句、直接、有推进感";
const DEFAULT_REASONING_STYLE = "根据自己可见的信息给出结论";
const DEFAULT_SYSTEM_PROMPT = "你是狼人杀对局中的一名玩家，只能依据你可见的信息行动。";

export const seedCharacters: readonly CharacterDefinition[] = [
  {
    id: "qin_chuan",
    name: "秦川",
    avatar: null,
    tags: ["default"],
    persona: DEFAULT_PERSONA,
    speakingStyle: DEFAULT_SPEAKING_STYLE,
    reasoningStyle: DEFAULT_REASONING_STYLE,
    systemPrompt: DEFAULT_SYSTEM_PROMPT,
    defaultModelBinding: null,
    enabled: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "lin_xia",
    name: "林夏",
    avatar: null,
    tags: ["default"],
    persona: DEFAULT_PERSONA,
    speakingStyle: DEFAULT_SPEAKING_STYLE,
    reasoningStyle: DEFAULT_REASONING_STYLE,
    systemPrompt: DEFAULT_SYSTEM_PROMPT,
    defaultModelBinding: null,
    enabled: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "zhou_zhi",
    name: "周知",
    avatar: null,
    tags: ["default"],
    persona: DEFAULT_PERSONA,
    speakingStyle: DEFAULT_SPEAKING_STYLE,
    reasoningStyle: DEFAULT_REASONING_STYLE,
    systemPrompt: DEFAULT_SYSTEM_PROMPT,
    defaultModelBinding: null,
    enabled: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "xu_tang",
    name: "许棠",
    avatar: null,
    tags: ["default"],
    persona: DEFAULT_PERSONA,
    speakingStyle: DEFAULT_SPEAKING_STYLE,
    reasoningStyle: DEFAULT_REASONING_STYLE,
    systemPrompt: DEFAULT_SYSTEM_PROMPT,
    defaultModelBinding: null,
    enabled: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "chen_mo",
    name: "陈墨",
    avatar: null,
    tags: ["default"],
    persona: DEFAULT_PERSONA,
    speakingStyle: DEFAULT_SPEAKING_STYLE,
    reasoningStyle: DEFAULT_REASONING_STYLE,
    systemPrompt: DEFAULT_SYSTEM_PROMPT,
    defaultModelBinding: null,
    enabled: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "shen_lan",
    name: "沈岚",
    avatar: null,
    tags: ["default"],
    persona: DEFAULT_PERSONA,
    speakingStyle: DEFAULT_SPEAKING_STYLE,
    reasoningStyle: DEFAULT_REASONING_STYLE,
    systemPrompt: DEFAULT_SYSTEM_PROMPT,
    defaultModelBinding: null,
    enabled: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
];
