import type { RoleDefinition } from "../core/role-definition";

const SEED_TIMESTAMP = "2026-06-27T00:00:00.000Z";

export const seedRoles: readonly RoleDefinition[] = [
  {
    id: "werewolf",
    name: "狼人",
    faction: "wolves",
    team: "wolf",
    mechanicKey: "wolf_kill",
    systemPrompt: "你是狼人阵营角色。夜晚与狼人队友共同选择一名玩家袭击，白天隐藏身份并推动放逐对狼人有利的目标。",
    actionPrompt: "夜晚请选择要袭击的目标，并给出简短理由。",
    visibilityRules: ["own_role", "wolf_teammates"],
    nightOrder: 10,
    defaultModelBinding: null,
    enabled: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "seer",
    name: "预言家",
    faction: "good",
    team: "god",
    mechanicKey: "seer_check",
    systemPrompt: "你是好人阵营神职角色。夜晚可以查验一名玩家的阵营信息，白天根据查验结果和发言推动放逐狼人。",
    actionPrompt: "夜晚请选择要查验的目标，并给出简短理由。",
    visibilityRules: ["own_role"],
    nightOrder: 20,
    defaultModelBinding: null,
    enabled: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "witch",
    name: "女巫",
    faction: "good",
    team: "god",
    mechanicKey: "witch_medicine",
    systemPrompt: "你是好人阵营神职角色。夜晚可根据规则使用解药或毒药，白天结合夜晚信息和发言寻找狼人。",
    actionPrompt: "夜晚请决定是否使用药剂，并给出简短理由。",
    visibilityRules: ["own_role", "witch_medicines"],
    nightOrder: 30,
    defaultModelBinding: null,
    enabled: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "villager",
    name: "平民",
    faction: "good",
    team: "villager",
    mechanicKey: "none",
    systemPrompt: "你是好人阵营平民角色。没有夜晚技能，需要通过白天发言、投票和逻辑判断找出狼人。",
    actionPrompt: null,
    visibilityRules: ["own_role"],
    nightOrder: null,
    defaultModelBinding: null,
    enabled: true,
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
];
